parameters:
    transmission_dir: null
    transmission_tmp: null
    transmission_hostname: null
    transmission_port: null
    transmission_authentication: null
    transmission_username: null
    transmission_password: null
